# Generated by Django 4.0.2 on 2022-02-22 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0002_items_user_phonenumber_receipt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='prize',
            new_name='unit_price',
        ),
        migrations.AddField(
            model_name='receipt',
            name='name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.items'),
        ),
        migrations.AddField(
            model_name='user',
            name='receipt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.receipt'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
            preserve_default=False,
        ),
    ]
